modLoader = "javafml"
loaderVersion = "*"
license = "CC0-1.0"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Me"
description = "This is an example description! Tell everyone what your mod is about!"
logoFile = "assets/${id}/icon.png"
logoBlur = false

[[mixins]]
config = "template-common.mixins.json"

[[mixins]]
config = "template-forge.mixins.json"